[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r backend/requirements.txt --no-cache-dir --quiet"
]

[start]
cmd = "bash /app/start.sh"
