"""Accounting entities and formal AR/AP subledgers.

Revision ID: a1b2c3d4e5f7
Revises: ff5a6b7c8d9e
Create Date: 2026-10-08

Adds party-level accounting identity without replacing the existing GL:
  accounting_entities -> entity_accounts -> accounts (control ledger).

Existing flats become MEMBER entities and existing vendors become VENDOR
entities. Existing virtual_account_number values remain payment identifiers;
they are not reused as accounting account numbers.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

revision = "a1b2c3d4e5f7"
down_revision = "ff5a6b7c8d9e"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if "accounting_entities" not in tables:
        op.create_table(
            "accounting_entities",
            sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column("society_id", UUID(as_uuid=True),
                       sa.ForeignKey("societies.id", ondelete="CASCADE"), nullable=False),
            sa.Column("entity_type", sa.String(20), nullable=False),
            sa.Column("entity_code", sa.String(64), nullable=False),
            sa.Column("display_name", sa.String(255), nullable=False),
            sa.Column("source_type", sa.String(40), nullable=True),
            sa.Column("source_id", UUID(as_uuid=True), nullable=True),
            sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.UniqueConstraint("society_id", "entity_type", "source_id",
                                name="uq_accounting_entity_source"),
            sa.UniqueConstraint("society_id", "entity_code",
                                name="uq_accounting_entity_code"),
        )
        op.create_index("ix_accounting_entities_society_id", "accounting_entities", ["society_id"])
        op.create_index("ix_accounting_entities_entity_type", "accounting_entities", ["entity_type"])
        op.create_index("ix_accounting_entities_source_id", "accounting_entities", ["source_id"])

    if "entity_accounts" not in tables:
        op.create_table(
            "entity_accounts",
            sa.Column("id", UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column("society_id", UUID(as_uuid=True),
                       sa.ForeignKey("societies.id", ondelete="CASCADE"), nullable=False),
            sa.Column("entity_id", UUID(as_uuid=True),
                       sa.ForeignKey("accounting_entities.id", ondelete="CASCADE"), nullable=False),
            sa.Column("control_account_id", UUID(as_uuid=True),
                       sa.ForeignKey("accounts.id", ondelete="RESTRICT"), nullable=False),
            sa.Column("subledger_type", sa.String(20), nullable=False),
            sa.Column("account_number", sa.String(30), nullable=False),
            sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.UniqueConstraint("society_id", "account_number",
                                name="uq_entity_account_number"),
            sa.UniqueConstraint("entity_id", "subledger_type",
                                name="uq_entity_account_subledger"),
        )
        op.create_index("ix_entity_accounts_society_id", "entity_accounts", ["society_id"])
        op.create_index("ix_entity_accounts_entity_id", "entity_accounts", ["entity_id"])
        op.create_index("ix_entity_accounts_control_account_id", "entity_accounts", ["control_account_id"])
        op.create_index("ix_entity_accounts_subledger_type", "entity_accounts", ["subledger_type"])

    # Codes are 'FLAT-'/'VENDOR-' + a 36-char UUID (41/43 chars); widen a pre-existing varchar(40) column.
    op.alter_column(
        "accounting_entities", "entity_code",
        existing_type=sa.String(40), type_=sa.String(64), existing_nullable=False,
    )

    # Seed accounting entities for existing operational parties. UUIDs are
    # generated by PostgreSQL; source IDs remain stable across the migration.
    op.execute("""
        INSERT INTO accounting_entities
            (id, created_at, updated_at, is_active, society_id, entity_type,
             entity_code, display_name, source_type, source_id, is_system)
        SELECT gen_random_uuid(), NOW(), NOW(), TRUE, w.society_id, 'member',
               'FLAT-' || f.id::text, f.flat_number, 'flat', f.id, TRUE
        FROM flats f
        JOIN wings w ON w.id = f.wing_id
        WHERE NOT EXISTS (
            SELECT 1 FROM accounting_entities e
            WHERE e.society_id = w.society_id
              AND e.entity_type = 'member'
              AND e.source_id = f.id
        )
    """)

    op.execute("""
        INSERT INTO accounting_entities
            (id, created_at, updated_at, is_active, society_id, entity_type,
             entity_code, display_name, source_type, source_id, is_system)
        SELECT gen_random_uuid(), NOW(), NOW(), TRUE, v.society_id, 'vendor',
               'VENDOR-' || v.id::text, v.company_name, 'vendor', v.id, TRUE
        FROM vendors v
        WHERE NOT EXISTS (
            SELECT 1 FROM accounting_entities e
            WHERE e.society_id = v.society_id
              AND e.entity_type = 'vendor'
              AND e.source_id = v.id
        )
    """)


def downgrade():
    op.drop_table("entity_accounts")
    op.drop_table("accounting_entities")
